### ISSUE TITLE
Почему бы не выполнить задаие так как оно описано ? 

### ISSUE THREAD

**Issue by Muxamedin** [KaraivanOK/hillel#1]
https://github.com/KaraivanOK/hillel/blob/d1cdcac7f9e476c7d45458dc87a25cd080270e5a/HW2/name.py#L1

4. Скрипт должен вывести  в консоль своё имя, нарисованное 'звёздочками'. Для выполнения этого задания надо использовать не только 

символы звёздочки и пробела, но и ESCAPE символы: \n и \t

**Comment by KaraivanOK** [comment]
Так получается меньше когда и сам результат красивее.

сб, 24 июл. 2021 г., 23:32 Mikel Bily ***@***.***>:

**Comment by Muxamedin** [comment]
Но задача была - использовать символы ESCAPE  \n и \t
А не воспользоваться библиотекой разработаной кем то другим

**Comment by KaraivanOK** [comment]
Почему вы поменяли оценку за ДЗ2?

вс, 25 июл. 2021 г., 10:51 Mikel Bily ***@***.***>:

**Comment by Muxamedin** [comment]
Так как одно из заданий выполнено на половину я должен был поставить такую
оценку. При этом я дал подсказку где и что исправить необходимо . Учитывая
все рекомендации я ожидал что вы исправите вашу работу . Так как этого не
произошло, есть другой механизм - пересдача например .

Ср, 28 июля 2021 г. в 01:39, KaraivanOK ***@***.***>:

**Comment by KaraivanOK** [comment]
Значит ставьте сразу ту оценку, которая получается. А так вы поставили одну
оценку, а через два дня поменяли на другую.

ср, 28 июл. 2021 г., 8:48 Mikel Bily ***@***.***>:

**Comment by Muxamedin** [comment]
Договорились.
   Я  поменял не через 2  по прошествии срока сдачи задания.Так как реакции на рекомендации не последовало.
С одной стороны можно быть таким четким и ставить оценку не меняя ее даже если кто то ошибся а потом поправил  :)
А можно было подсказать выполнявшему задание где у него что нужно подправить согласно требованиям.



Mikel Bily
Staff Software Engineer
CloudBees, Inc.

**Comment by KaraivanOK** [comment]
Оценку в 99 баллов я получил после дедлайна. А если кто-то ошибся и решил
исправить, так для этого у него есть 2-е пересдачи.

ср, 28 июл. 2021 г., 10:36 Mikel Bily ***@***.***>:

> Договорились.
> Я поменял не через 2 по прошествии срока сдачи задания.Так как реакции на
> рекомендации не последовало.
> С одной стороны можно быть таким четким и ставить оценку не меняя ее даже
> если кто то ошибся а потом поправил :)
> А можно было подсказать выполнявшему задание где у него что нужно
> подправить согласно требованиям.
>
>
>
> Mikel Bily
> Staff Software Engineer
> CloudBees, Inc.
>
>
>
>

**Comment by KaraivanOK** [comment]
Исправил ещё во вторник, но нет смысла пересдавать, т.к. вместо 90 баллов получу 89.
https://github.com/KaraivanOK/hillel/blob/main/HW2/name1.py
