### ISSUE TITLE
Рекомендация 

### ISSUE THREAD

**Issue by Muxamedin** [KaraivanOK/hillel#2]
Обратите внимание на требования задачи к тому что должно выводить приложение 
https://github.com/KaraivanOK/hillel/blob/7092942424fc0b42071a97b70dd9e9560563775d/HW4/dve_odinakovye_cifri.py#L2

**Comment by KaraivanOK** [comment]
Не совсем понимаю вас. В условии сказано: необходимо определить есть две
одинаковые цифры в числе или нет, что программа и делает.

вт, 3 авг. 2021 г., 11:21 Mikel Bily ***@***.***>:
