### ISSUE TITLE
Рекомендация 

### ISSUE THREAD

**Issue by Muxamedin** [KaraivanOK/hillel#3]
Обратите внимание на требованя задачи к тому что должно выводится
https://github.com/KaraivanOK/hillel/blob/7092942424fc0b42071a97b70dd9e9560563775d/HW4/odinakovye_cifri_ryadom.py#L11

**Comment by KaraivanOK** [comment]
Если вас не затруднит, то объясните что не так?

вт, 3 авг. 2021 г., 11:24 Mikel Bily ***@***.***>:

**Comment by Muxamedin** [comment]
Задча сделана верно. Все в порядке.
Но в примере указано что должно было водится :  Да или Нет
 В  будущем мы будем делать задачи в которых необходимо что бы их реализация четко соответствовала  условиям задачи в том числе то что должно выводится и как, так как на них же и будем писать юнит тесты. 
 Подсказываю, обращать внимание на такие моменты :)
